title: A journey into continued learning...
author: Sam Hansen
email: sam.hans24@yahoo.com

# social links
twitter_username: samuelmhansen
github_username: sam-hansen

show_excerpts: false
theme: minima
